### ISSUE TITLE
Option to separate control of puzzle from puzzle itself

### ISSUE THREAD

**Issue by daviddeutsch** [aren227/TheWitness-LockScreen#1]
It's a little hard to see the puzzle while I'm solving it. Maybe there could be a mode where my lower screen half controls the puzzle (and maybe has a "shadow" of the puzzle with just the outline) while the actual puzzle is in the upper half?
As an example: that might also help with the "symmetry" puzzles - because here, you can only ever control the line you started with, but you would kind of expect to be able to move both lines once you have started them - a "lower screen half control" could have just the line that you are actually drawing and not the mirrored one, which would make this more clear:

![control-double](https://user-images.githubusercontent.com/630246/90969610-a0442980-e4fa-11ea-9e80-591e486cada1.png)

So I would control the upper puzzle by moving my thumb over the lower puzzle.

**Comment by aren227** [comment]
Implemented in 92d3dcfe4488a352b4fbcfcd61b75e76f1cd0022:

![Screenshot_1598272135](https://user-images.githubusercontent.com/14082448/91046230-02b03d80-e653-11ea-8ba0-0da06481fde7.png)

**Comment by daviddeutsch** [comment]
Wow, this one went over much quicker than I thought! Sweet!

I do have one point of criticism - I think having an outline view is too… visually imposing. It kind of distracts from the puzzle itself. Do consider making it more of a shadow like so:

![grafik](https://user-images.githubusercontent.com/630246/91162673-aee23a80-e6cc-11ea-8398-dab5d7e6bb61.png)

(just a raw mockup based on my earlier mockup)

**Comment by daviddeutsch** [comment]
@aren227 Wow, this one went over much quicker than I thought! Sweet!

I do have one point of criticism - I think having an outline view is too… visually imposing. It kind of distracts from the puzzle itself. Do consider making it more of a shadow like so:

![grafik](https://user-images.githubusercontent.com/630246/91162673-aee23a80-e6cc-11ea-8398-dab5d7e6bb61.png)

(just a raw mockup based on my earlier mockup)

**Comment by aren227** [comment]
I made a shadow line to transparent. Please check the latest build.

**Comment by daviddeutsch** [comment]
@aren227 perfect! Thank you!
