### ISSUE TITLE
Glitch on Entry Area #2

### ISSUE THREAD

**Issue by daviddeutsch** [aren227/TheWitness-LockScreen#11]
![Screenshot_20200825-200854](https://user-images.githubusercontent.com/630246/91282934-422d7580-e78a-11ea-938f-0b9706bff4a3.png)

The Starting Circle has a cut-in that shouldn't happen.

**Comment by aren227** [comment]
Are you sure you are using the latest build 36e855f8458b6d05c37d46ba16267fd7f2591def? It was fixed in b7c3c318a76ddecddc7d540a900e9884a0a7e4be.

**Comment by daviddeutsch** [comment]
@aren227 yup, you're right. That was an older Version and I tested around a bit but couldn't reproduce this with the latest Version.

The "skip to the next puzzle" really helps with this kind of testing!
