### ISSUE TITLE
Different "Profiles" for Play, Lock etc.

### ISSUE THREAD

**Issue by daviddeutsch** [aren227/TheWitness-LockScreen#2]
Selecting which "locks" I want to use may differ from what I want to do in "play" mode. So maybe I don't want to include more complex puzzles on my lock screen - I'd have to switch back and forth the options which is cumbersome.

My proposal for a solution would be to add the ability to set up a number of different "profiles" and assign one of them to the Lock mode.

I also might want to have a different "Play" mode every now and then. Like maybe I just want to train for the Challenge puzzles (so there, just enable that one) or maybe I want to have a "chill" profile and a "break my brain" profile.

In general, the more puzzle types you're going to add, the more of a chore it will be to select them from the Gallery as it is required for now.

**Comment by aren227** [comment]
You can now use different profiles. Please check the latest build and tell me your thoughts!

**Comment by daviddeutsch** [comment]
@aren227 Well, it's exactly what I was looking for, so thanks a lot!
