### ISSUE TITLE
Jungle and Video Room Puzzle crash the app

### ISSUE THREAD

**Issue by daviddeutsch** [aren227/TheWitness-LockScreen#23]
Sorry, seems like this is a consistent bug :-/

**Comment by aren227** [comment]
Sorry, but I can't replicate the issue. Can you tell me more detailed information?

**Comment by daviddeutsch** [comment]
Not sure how, really. I go the regular path: Gallery -> New -> Random -> Create. As soon as I then select Jungle or Video Room, the first time it skips back to "Gallery", the second time, the App crashes.

How can I be more specific here?

**Comment by aren227** [comment]
Ohhhh.. I didn't know that jungle and video room puzzle could be selected from random mode. I will fix it soon.

**Comment by daviddeutsch** [comment]
:grinning: I didn't even think about checking the pattern one. Good thing we could clear this up!
