### ISSUE TITLE
"Update Available" when on the beta version

### ISSUE THREAD

**Issue by daviddeutsch** [aren227/TheWitness-LockScreen#27]
![grafik](https://user-images.githubusercontent.com/630246/105983232-b4d3b180-6098-11eb-9f36-84c61d496383.png)

This is kind of just a minor annoyance, but something in the app should understand that 0.3 is actually newer than 0.2 :joy:

**Comment by aren227** [comment]
```
if (CURRENT_VERSION != RELEASE_VERSION)
    showUpdateAvailableDialog();
```
💥 BOOM! It works!! (mostly)

**Comment by daviddeutsch** [comment]
WOOP WOOP :pray:
