### ISSUE TITLE
10x10 puzzles

### ISSUE THREAD

**Issue by Pyato4ka** [aren227/TheWitness-LockScreen#28]
Thank you for your great work and for adding ability to remove line! I want to create a 10x10 puzzle like this:
![Act_1_3](https://user-images.githubusercontent.com/42499386/106267923-0a43c600-6233-11eb-9459-1319e6000976.jpg)
But if I correctly understood, there is a 7x7 limit. Could you increase it to 10x10, please?
Also, could you add a possibility to create right/left/diagonal ends on the corners like there:
![Act_1_5](https://user-images.githubusercontent.com/42499386/106268138-57279c80-6233-11eb-93d3-fd2e737923c8.jpg)

**Comment by aren227** [comment]
Right. There is a limit because when validating polyomino, it used bit mask for performance reason. But recently i changed algorithm so it can works with any dimension.

**Comment by daviddeutsch** [comment]
@aren227 while you're at it, could you also have a look at line thickness? I think the outline of the puzzle should be thinner. With a 7x7 it looks rather crammed:

![grafik](https://user-images.githubusercontent.com/630246/106339155-01d0a700-6296-11eb-9e07-923543618078.png)

**Comment by daviddeutsch** [comment]
Another comparison:

Trying to recreate this:

![grafik](https://user-images.githubusercontent.com/630246/106340428-0eef9500-629a-11eb-87a5-c4e9d84a7e4d.png)

resulted in this:

![grafik](https://user-images.githubusercontent.com/630246/106340462-27f84600-629a-11eb-8671-80b434a55fb6.png)

**Comment by aren227** [comment]
Now you can make 10x10 puzzles with properly adjuested line thickness. Check the latest beta build.

**Comment by daviddeutsch** [comment]
Yup, looks good now :+1:
