### ISSUE TITLE
Make Gallery selection more obvious

### ISSUE THREAD

**Issue by daviddeutsch** [aren227/TheWitness-LockScreen#9]
It's somewhat hard to make out what is and isn't selected in the Gallery, maybe add a colored outline to make it extra obvious?

![Screenshot_20200823-043000](https://user-images.githubusercontent.com/630246/90969830-7cceae00-e4fd-11ea-857d-4bb2ba527150.png)

Here, Treehouse #3 is selected but it's barely visible.

**Comment by aren227** [comment]
> Also: Why is the Gallery loading so, so slowly? Is it generating a new full puzzle and then displaying a screenshot of that? This code here seems to suggest that it does:
> 
> https://github.com/aren227/TheWitness-LockScreen/blob/master/app/src/main/java/com/aren/thewitnesspuzzle/GalleryActivity.java#L98
> 
> that might not be a good idea. At the very least, pre-render all of these when the game boots up first.

Fixed in 47b8b1285d54d1005b9d58cef6b890359f5867ca and 79961478383794700b7a645ea08351c08b765c4e.

Also, I added a white outline like The Witness does.

![Screenshot_1598257046](https://user-images.githubusercontent.com/14082448/91021733-2497c900-e62f-11ea-8511-3f4c896c5585.png)
